services:
  codebreaker.gameapis:
    image: codebreaker/gameapis:basta
    container_name: codebreaker.gameapis
    hostname: gameapis
    ports:
      - "8080:8080"
  codebreaker.bot:
    image: codebreaker/bot:latest
    container_name: codebreaker.bot
    hostname: bot
    depends_on:
      - codebreaker.gameapis
    ports:
      - "8081:8080"     
    environment:
      APIBase: "http://gameapis:8080"
